name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4  # FRISSÍTVE
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7.6'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --collect-all multiprocessing analyzer.py
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4  # FRISSÍTVE
      with:
        name: FlacAnalyzerEXE
        path: dist/analyzer.exe
